fairplens/urls.py
from django.urls import path

from . import views

app_name = 'fairplens'
urlpatterns = [
    # ex: /fairplens/
    path('', views.HomepageView.as_view(), name='homepage'),

    path('user/', views.UserDetailView.as_view(), name='user_detail'),

    path('ticket/', views.TicketIndexView.as_view(), name='ticket_index'),
    path('ticket/create/', views.TicketCreateFormView.as_view(), name='ticket_create_form'),
    # ex: /fairplens/ticket/3/verify
    path('ticket/<int:pk>/verify', views.TicketVerifyFormView.as_view(), name='ticket_verify_form'),
    # ex: /fairplens/ticket/5
    path('ticket/<int:pk>/', views.TicketDetailView.as_view(), name='ticket_detail'),

    # ex: /fairplens/casualmatch/12
    path('casualmatch/<int:pk>/', views.CasualMatchDetailView.as_view(), name='casual_match_detail'),

    # ex: /fairplens/tournamentmatch/53
    path('tournamentmatch/<int:pk>/', views.TournamentMatchDetailView.as_view(), name='tournament_match_detail'),

    # ex: /fairplens/singleeliminationtournament/5
    path('singleeliminationtournament/<int:pk>/', views.SingleEliminationTournamentDetailView.as_view(), name='single_elimination_tournament_detail'),
    path('singleeliminationtournament/<int:pk>/addmatch/', views.AddTournamentMatchFormView.as_view(), name='add_tournament_match_form'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('fairplens/', include('fairplens.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

urlpatterns += staticfiles_urlpatterns()

fairplens/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser

from datetime import datetime

"""
models.User :
- username
- first_name (optional, blank=True)
- last_name (optional, blank=True)
- email (optional, blank=True)
- password (hash and metadata)
x groups
- user_permissions (many-to-many with Permission)
- is_staff (can access admin site or not)
- is_active (better deactivate an account than delete it)
- is_superuser (all permissions without assigning them)
- last_login (datetime)
- date_joined
"""

class Member(AbstractUser):
    memberships = models.JSONField(null=True, blank=True)
    elo = models.IntegerField(default=0)



class Ticket(models.Model):
    class Meta:
        permissions = [('can_verify_ticket', 'Can verify ticket')]

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tickets_created')
    verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.DO_NOTHING, related_name='verified_tickets')

    elo_registered = models.BooleanField(default=False)
    who_won = models.BooleanField(default=False) # False for blue, True for red
    blue_score = models.SmallIntegerField(default=0)
    red_score = models.SmallIntegerField(default=0)
    date = models.DateTimeField('Date', default=datetime.now)

    blue_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tickets_played_blue_side')
    red_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tickets_played_red_side')

    def __str__(self):

        pp_blue = 'B : '
        pp_red = 'R : '
        winner = 'Winner : Red' if self.who_won else 'Winner : Blue'

        for i in self.blue_side.all():
            pp_blue += i.username + ', '

        for i in self.red_side.all():
            pp_red += i.username + ', '

        return str(self.pk)+' | '+pp_blue[:-2]+' \\'+str(self.blue_score)+'/ | \\'+str(self.red_score)+'/ '+pp_red[:-2]+' | '+winner



class CasualMatch(models.Model):
    elo_registered = models.BooleanField(default=False)
    who_won = models.BooleanField(default=False)
    blue_score = models.SmallIntegerField(default=0)
    red_score = models.SmallIntegerField(default=0)
    date = models.DateTimeField('Date', default=datetime.now)

    blue_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='casual_matches_played_blue_side')
    red_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='casual_matches_played_red_side')

    origin_ticket = models.OneToOneField(Ticket, null=True, on_delete=models.CASCADE, related_name='related_match')

    def __str__(self):

        pp_blue = 'B : '
        pp_red = 'R : '
        winner = 'Winner : Red' if self.who_won else 'Winner : Blue'

        for i in self.blue_side.all():
            pp_blue += i.username + ', '

        for i in self.red_side.all():
            pp_red += i.username + ', '

        return str(self.pk)+' | '+pp_blue[:-2]+' \\'+str(self.blue_score)+'/ | \\'+str(self.red_score)+'/ '+pp_red[:-2]+' | '+winner



class TournamentMatch(models.Model):
    # Possibility to give a name to easily find a match in a given tournament
    name = models.CharField(blank=True, max_length=64)

    who_won = models.BooleanField(default=False)
    blue_score = models.SmallIntegerField(default=0)
    red_score = models.SmallIntegerField(default=0)
    date = models.DateTimeField('Date', default=datetime.now)

    blue_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tournament_matches_played_blue_side')
    red_side = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tournament_matches_played_red_side')

    # Used for the tournament matches tree
    previous_matches = models.ManyToManyField("self", blank=True, symmetrical=False)

    def __str__(self):

        if self.name == '':
            pp_blue = 'B : '
            pp_red = 'R : '
            winner = 'Winner : Red' if self.who_won else 'Winner : Blue'

            for i in self.blue_side.all():
                pp_blue += i.username + ', '

            for i in self.red_side.all():
                pp_red += i.username + ', '

            return str(self.pk)+' | '+pp_blue[:-2]+' \\'+str(self.blue_score)+'/ | \\'+str(self.red_score)+'/ '+pp_red[:-2]+' | '+winner

        else:
            return self.name

class SingleEliminationTournament(models.Model):
    name = models.CharField(blank=True, max_length=64)
    organisers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='single_elimination_tournaments_organised')
    matches = models.ManyToManyField(TournamentMatch, blank=True, related_name='tournament')
    start_date = models.DateTimeField('Start date', default=datetime.now)
    end_date = models.DateTimeField('End date', default=datetime.now)

    # Date past which the organisers can't change the tournament and its matches anymore
    end_permission_date = models.DateTimeField('End of the permissions', default=datetime.now)

    def __str__(self):
        if self.name == '':
            return str(self.pk) + " | Single elimination tournament - [ " + str(self.start_date) + " ; " + str(self.end_date) + " ]"
        else:
            return str(self.pk) + " | " + self.name

fairplens/forms.py
from django import forms
from .models import Ticket, TournamentMatch

class TicketCreateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'
        exclude = ['creator', 'verified', 'verified_by']
        labels = {
            'who_won': 'Check if Red Team won, leave unchecked if Blue Team won :',
        }

class TicketVerifyForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['verified']

class AddTournamentMatchForm(forms.ModelForm):
    class Meta:
        model = TournamentMatch
        fields = '__all__'
        labels = {
            'who_won': 'Check if Red Team won, leave unchecked if Blue Team won :',
        }

fairplens/views.py
from tokenize import Single
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Messages displayed when an action is successful or unsuccessful
from django.contrib import messages

# Logical expressions in .filter() for ManyToMany fields
from django.db.models import Q

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
User = get_user_model()

from .models import Ticket, CasualMatch, TournamentMatch, SingleEliminationTournament
from .forms import TicketCreateForm, TicketVerifyForm, AddTournamentMatchForm

# Row-level permissions
from guardian.shortcuts import assign_perm, remove_perm



class HomepageView(generic.ListView):
    template_name = 'fairplens/homepage.html'
    context_object_name = 'latest_casual_matches_list'

    def get_queryset(self):
        return CasualMatch.objects.order_by('-date')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_single_elimination_tournaments_list'] = SingleEliminationTournament.objects.order_by('-start_date')[:5]
        return context



class UserDetailView(generic.ListView):
    model = User
    template_name = 'fairplens/user_detail.html'
    context_object_name = 'casual_matches_list'

    # Get all matches played on either side
    def get_queryset(self):
        if self.request.user.is_authenticated:
            return CasualMatch.objects.filter(Q(red_side=self.request.user) | Q(blue_side=self.request.user)).distinct().order_by('-date')
        else:
            pass



class TicketDetailView(generic.DetailView):
    model = Ticket
    template_name = 'fairplens/ticket_detail.html'

    # Override function to check if the current user has the right permission
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['has_verify_permission'] = self.request.user.has_perm('can_verify_ticket', context['ticket'])
        return context

class TicketIndexView(generic.ListView):
    model = Ticket
    template_name = 'fairplens/ticket_index.html'
    context_object_name = 'ticket_list'    

    def get_queryset(self):
        # Get all tickets that can be verified by the user
        verifiable = []
        not_verified = Ticket.objects.filter(verified=False)
        for ticket in not_verified :
            if self.request.user.has_perm('can_verify_ticket', ticket) :
                verifiable.append(ticket.id)
        return Ticket.objects.filter(pk__in=verifiable)

class TicketCreateFormView(generic.edit.FormView):
    form_class = TicketCreateForm
    template_name = 'fairplens/ticket_create_form.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        success_url = '/fairplens/ticket/create/'

        if not request.user.is_authenticated :
            messages.error(request, "Please log in to create a ticket. Ticket not created.")
        else :
            # The form data has to be valid
            if form.is_valid():

                blue_side = form.cleaned_data['blue_side']
                red_side = form.cleaned_data['red_side']

                blue_score = form.cleaned_data['blue_score']
                red_score = form.cleaned_data['red_score']
                who_won = form.cleaned_data['who_won']

                # The winner must have the most points (who_won = True iff Red won, Blue otherwise)
                if ((not who_won) and (blue_score > red_score)) or (who_won and (blue_score < red_score)):
                    # The ticket creator must be a player of the match
                    if (request.user in blue_side) or (request.user in red_side):

                        elo_registered = form.cleaned_data['elo_registered']
                        date = form.cleaned_data['date']

                        # Create the ticket with cleaned data and save it in the database
                        ticket = Ticket(creator=request.user, elo_registered=elo_registered, who_won=who_won, blue_score=blue_score, red_score=red_score, date=date)
                        ticket.save()
                        ticket.blue_side.set(blue_side)
                        ticket.red_side.set(red_side)

                        # Assign ticket verify permissions to the players belonging to the opposite side of the creator
                        if request.user in blue_side:
                            for player in red_side:
                                assign_perm('fairplens.can_verify_ticket', player, ticket)
                        else:
                            for player in blue_side:
                                assign_perm('fairplens.can_verify_ticket', player, ticket)

                        messages.success(request, "Ticket created ! The other team can now verify it.")
                        return HttpResponseRedirect(success_url)
                    else:
                        messages.error(request, "Only the players that took part in a match can create its ticket. Ticket not created.")
                else:
                    messages.error(request, "The winning team must have stricly more points than the other. Ticket not created.")

        return render(request, self.template_name, {'form': form})

class TicketVerifyFormView(generic.edit.FormView):
    form_class = TicketVerifyForm
    template_name = 'fairplens/ticket_verify_form.html'

    def get(self, request, pk):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        form = self.form_class(request.POST)
        success_url = '/fairplens/'
        fail_url = '/fairplens/ticket/' + str(pk) + '/'

        if form.is_valid():
            ticket = Ticket.objects.get(pk=pk)

            # Ticket already verified
            if ticket.verified:
                messages.error(request, "This ticket has already been verified.")
                return HttpResponseRedirect(fail_url)

            else:
                if request.user.has_perm('can_verify_ticket', ticket):
                    verified = form.cleaned_data['verified']
                    if verified:
                        # Successful verification
                        ticket.verified = verified
                        ticket.verified_by = request.user
                        ticket.save()

                        match = CasualMatch(elo_registered=ticket.elo_registered, who_won=ticket.who_won, blue_score=ticket.blue_score, red_score=ticket.red_score, date=ticket.date, origin_ticket=ticket)
                        match.save()
                        match.blue_side.set(ticket.blue_side.all())
                        match.red_side.set(ticket.red_side.all())

                        # Remove ticket verify permissions from the opposite side of the creator
                        if request.user in ticket.blue_side.all():
                            for player in ticket.blue_side.all():
                                remove_perm('fairplens.can_verify_ticket', player, ticket)
                        else:
                            for player in ticket.red_side.all():
                                remove_perm('fairplens.can_verify_ticket', player, ticket)

                        messages.success(request, "Ticket verified ! The corresponding match has been created.")
                        return HttpResponseRedirect(success_url)
                # User doesn't have the right permission to validate the ticket
                else:
                    messages.error(request, "You don't have permission to verify this ticket. Ticket not verified.")
                    return HttpResponseRedirect(fail_url)

        return render(request, self.template_name, {'form': form})



class CasualMatchDetailView(generic.DetailView):
    model = CasualMatch
    context_object_name = 'match'
    template_name = 'fairplens/casual_match_detail.html'

class TournamentMatchDetailView(generic.DetailView):
    model = TournamentMatch
    context_object_name = 'match'
    template_name = 'fairplens/tournament_match_detail.html'

    # Get the previous matches
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_match = TournamentMatch.objects.get(pk=self.kwargs['pk'])
        next_match = None
        for match in TournamentMatch.objects.get(pk=self.kwargs['pk']).tournament.first().matches.all():
            if current_match in match.previous_matches.all():
                next_match = match
        context['previous_match_list'] = current_match.previous_matches.all()
        context['next_match'] = next_match
        return context



class SingleEliminationTournamentDetailView(generic.DetailView):
    model = SingleEliminationTournament
    context_object_name = 'tournament'
    template_name = 'fairplens/single_elimination_tournament_detail.html'

    # Get the list of matches
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tournament_match_list'] = SingleEliminationTournament.objects.get(pk=self.kwargs['pk']).matches.all()
        return context

class AddTournamentMatchFormView(generic.edit.FormView):
    form_class = AddTournamentMatchForm
    template_name = 'fairplens/add_tournament_match_form.html'

    def get(self, request, pk):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        form = self.form_class(request.POST)
        success_url = '/fairplens/singleeliminationtournament/' + str(pk) + '/addmatch/'
        fail_url = '/fairplens/singleeliminationtournament/' + str(pk) + '/'

fairplens/templates/fairplens/add_tournament_match_form.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Adding a tournament match</h1>

  <br>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <input type="submit" value="Submit">
  </form> 

{% endblock %}

fairplens/templates/fairplens/casual_match_detail.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Casual match detail</h1>

  <br>

  <p>This match (id : {{ match.pk }}) was played at : {{ match.date }}</p>
  {% if match.elo_registered %}
    <p>It counted for the elo system.</p>
  {% else %}
    <p>It didn't count for the elo system.</p>
  {% endif %}
  <p>Players on the blue side :</p>
  <ul>
    {% for player in match.blue_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Players on the red side :</p>
  <ul>
    {% for player in match.red_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Winner side : {% if match.who_won %} red. {% else %} blue. {% endif %}</p>
  <p>Score : Blue {{ match.blue_score }} | {{ match.red_score }} Red.</p>

  <p><a href="{% url 'fairplens:ticket_detail' match.origin_ticket.pk %}">Origin ticket</a></p>

{% endblock %}

fairplens/templates/fairplens/homepage.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Homepage</h1>

  <br>

  {% if user.is_authenticated %}
    <h4><a href="{% url 'fairplens:ticket_create_form' %}">Create a ticket</a></h4>
    <h4><a href="{% url 'fairplens:ticket_index' %}">See if you can verify some tickets</a></h4>
    <h4><a href="{% url 'fairplens:user_detail' %}">View your career details</a></h4>
  {% endif %}

  <br>

  <h3>Here are the latest casual matches :</h3>

  {% if latest_casual_matches_list %}
    <ul>
      {% for casual_match in latest_casual_matches_list %}
        <li><a href="{% url 'fairplens:casual_match_detail' casual_match.pk %}">{{ casual_match }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No matches are available.</p>
  {% endif %}

  <br>

  <h3>Here are the latest single elimination tournaments :</h3>

  {% if latest_single_elimination_tournaments_list %}
    <ul>
      {% for tournament in latest_single_elimination_tournaments_list %}
        <li><a href="{% url 'fairplens:single_elimination_tournament_detail' tournament.pk %}">{{ tournament }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No tournaments are available.</p>
  {% endif %}

{% endblock %}

fairplens/templates/fairplens/single_elimination_tournament_detail.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">{{ tournament }}</h1>

  <br>

  <h4><a href="{% url 'fairplens:add_tournament_match_form' tournament.pk %}">Add a match</a></h4>

  <br>

  <h3>Matches of the tournament :</h3>

  {% if tournament_match_list %}
    <ul>
      {% for match in tournament_match_list %}
        <li><a href="{% url 'fairplens:tournament_match_detail' match.pk %}">{{ match }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no matches in this tournament.</p>
  {% endif %}

{% endblock %}

fairplens/templates/fairplens/ticket_create_form.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Create a ticket</h1>

  <br>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <input type="submit" value="Submit">
  </form> 

{% endblock %}

fairplens/templates/fairplens/ticket_detail.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Ticket detail</h1>

  <br>

  <p>This ticket (id : {{ ticket.pk }}) has been created by {{ ticket.creator.username }}. The match was played at : {{ ticket.date }}</p>
  {% if ticket.elo_registered %}
    <p>It counted for the elo system.</p>
  {% else %}
    <p>It didn't count for the elo system.</p>
  {% endif %}
  <p>Players on the blue side :</p>
  <ul>
    {% for player in ticket.blue_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Players on the red side :</p>
  <ul>
    {% for player in ticket.red_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Winner side : {% if ticket.who_won %} red. {% else %} blue. {% endif %}</p>
  <p>Score : Blue {{ ticket.blue_score }} | {{ ticket.red_score }} Red.</p>

  {% if ticket.verified %}
    <p>This ticket has been verified by {{ ticket.verified_by.username }} and the corresponding match created.</p>
  {% elif has_verify_permission %}
    <p>This ticket has not yet been verified, but you can <a href="{% url 'fairplens:ticket_verify_form' ticket.pk %}">verify it !</a></p>
  {% else %}
    <p>This ticket has not yet been verified but you do not have permission to do so.</p>
  {% endif %}

{% endblock %}

fairplens/templates/fairplens/ticket_index.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Ticket index</h1>

  <br>

  {% if user.is_authenticated %}

    <h3>Here are the tickets that you can verify :</h3>

    {% if ticket_list %}
      <ul>
        {% for ticket in ticket_list %}
          <li><a href="{% url 'fairplens:ticket_detail' ticket.pk %}">{{ ticket }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No tickets are available for verification.</p>
    {% endif %}

  {% else %}
    <h3>Please log in to view the tickets.</h3>
  {% endif %}

{% endblock %}

fairplens/templates/fairplens/ticket_verify_form.html
{% extends "base.html" %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

fairplens/templates/fairplens/tournament_match_detail.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Tournament match detail</h1>

  <br>

  <h4>{{ match.name }}</h4>

  <br>

  <p>This match (id : {{ match.pk }}) was played at : {{ match.date }}</p>
  <p>Players on the blue side :</p>
  <ul>
    {% for player in match.blue_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Players on the red side :</p>
  <ul>
    {% for player in match.red_side.all %}
      <li>{{ player.username }}</li>
    {% endfor %}
  </ul>
  <p>Winner side : {% if match.who_won %} red. {% else %} blue. {% endif %}</p>
  <p>Score : Blue {{ match.blue_score }} | {{ match.red_score }} Red.</p>

  <h3>Previous matches in the tournament tree :</h3>

  {% if previous_match_list %}
    <ul>
      {% for previous_match in previous_match_list %}
        <li><a href="{% url 'fairplens:tournament_match_detail' previous_match.pk %}">{{ previous_match }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There were no previous matches in the tournament tree.</p>
  {% endif %}

  <br>

  <h3>Next match :</h3>

  {% if next_match %}
    <p><a href="{% url 'fairplens:tournament_match_detail' next_match.pk %}">{{ next_match }}</a></p>
  {% else %}
    <p>There was no next match in the tournament tree.</p>
  {% endif %}

{% endblock %}

fairplens/templates/fairplens/user_detail.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align:center">Career details</h1>

  {% if user.is_authenticated %}

    <p>Hello again, {{ user.username }} !</p>
    <p>Name : {{ user.first_name }} {{ user.last_name }}.</p>
    <p>Email : {{ user.email }}</p>
    <p>Last login : {{ user.last_login }}</p>
    <p>Date joined : {{ user.date_joined }}</p>

    <br>

    <h3>Here are your casual matches :</h3>

    {% if casual_matches_list %}
      <ul>
      {% for casual_match in casual_matches_list %}
        <li><a href="{% url 'fairplens:casual_match_detail' casual_match.pk %}">{{ casual_match }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No matches are available.</p>
    {% endif %}

  {% else %}
    <h3>Please log in to view your carrer details.</h3>
  {% endif %}

{% endblock %}